import { useMeta } from '@mikata/kit/head';
import { CodeBlock, highlight } from '../../components/CodeBlock';
import { Link } from '@mikata/router';

export const nav = { title: 'Your first app', section: 'Start', order: 5 };

const todoList = await highlight(
  `import { signal, computed, render, show, each } from 'mikata';

function TodoList() {
  const [todos, setTodos] = signal<{ id: number; text: string; done: boolean }[]>([]);
  const [input, setInput] = signal('');
  const remaining = computed(() => todos().filter((t) => !t.done).length);

  const add = () => {
    if (!input().trim()) return;
    setTodos([...todos(), { id: Date.now(), text: input(), done: false }]);
    setInput('');
  };

  const toggle = (id: number) =>
    setTodos(todos().map((t) => (t.id === id ? { ...t, done: !t.done } : t)));

  return (
    <div>
      <input
        value={input()}
        onInput={(e) => setInput(e.currentTarget.value)}
        onKeydown={(e) => e.key === 'Enter' && add()}
      />
      <button onClick={add}>Add</button>

      <ul>
        {each(todos, (todo) => (
          <li
            style={{ textDecoration: todo.done ? 'line-through' : 'none' }}
            onClick={() => toggle(todo.id)}
          >
            {todo.text}
          </li>
        ))}
      </ul>

      {show(
        () => todos().length > 0,
        () => <p>{remaining()} remaining</p>
      )}
    </div>
  );
}

render(() => <TodoList />, document.getElementById('app')!);`,
  'tsx',
);
const runCommands = await highlight(
  `pnpm create mikata todo-demo --template minimal
cd todo-demo
pnpm install
pnpm dev`,
  'bash',
);

export default function FirstApp() {
  useMeta({
    title: 'Your first app - Mikata',
    description: 'Build a small todo app with Mikata signals, control flow, and DOM rendering.',
  });

  return (
    <article>
      <h1>Your first app</h1>
      <p>
        A full todo list in one file. This is idiomatic Mikata - the
        component function runs once, signals drive updates, and{' '}
        <code>each()</code>/<code>show()</code> handle reactive lists and
        conditional branches without re-running the surrounding component.
      </p>

      <h2>Create the app</h2>
      <p>
        Start from the minimal template, then replace <code>src/App.tsx</code>
        or <code>src/main.tsx</code> with the example below.
      </p>
      <CodeBlock html={runCommands} />

      <h2>Todo list</h2>
      <CodeBlock html={todoList} />

      <h2>What's happening</h2>
      <ul>
        <li>
          <code>signal</code> returns <code>[getter, setter]</code>. The
          getter is a function - call it to read, and Mikata tracks the
          read in the surrounding reactive context.
        </li>
        <li>
          <code>computed</code> is a derived signal. It re-runs only when
          a dependency it read changes.
        </li>
        <li>
          <code>each</code> renders a keyed reactive list without
          re-creating rows. <code>show</code> does the same for a single
          branch.
        </li>
        <li>
          Event handlers receive native events, typed against the element
          they're bound to - <code>e.currentTarget.value</code> is typed
          for you.
        </li>
      </ul>

      <h2>Where next</h2>
      <ul>
        <li>
          <Link to="/core/reactivity">Reactivity</Link> explains signals,
          computed values, batching, and cleanup.
        </li>
        <li>
          <Link to="/core/control-flow">Control flow</Link> covers list and
          branch helpers in more depth.
        </li>
        <li>
          <Link to="/start/project-structure">Project structure</Link> maps the
          files generated by the scaffold.
        </li>
      </ul>
    </article>
  );
}
