import { useMeta } from '@mikata/kit/head';
import { Link } from '@mikata/router';
import { CodeBlock, highlight } from '../../components/CodeBlock';

export const nav = { title: 'Project structure', section: 'Start', order: 6 };

const baseTree = await highlight(
  `my-app/
  index.html
  package.json
  tsconfig.json
  vite.config.ts
  src/
    main.tsx
    App.tsx`,
  'text',
);

const routerTree = await highlight(
  `my-app/
  src/
    main.tsx
    App.tsx
    router.tsx
    pages/
      Home.tsx
      About.tsx`,
  'text',
);

const kitTree = await highlight(
  `my-app/
  index.html
  server.js
  src/
    entry-client.tsx
    entry-server.tsx
    mikata-env.d.ts
    routes/
      _layout.tsx
      index.tsx
      about.tsx
      404.tsx
      api/
        ping.ts`,
  'text',
);

export default function ProjectStructure() {
  useMeta({
    title: 'Project structure - Mikata',
    description: 'Understand the files generated by create-mikata.',
  });

  return (
    <article>
      <h1>Project structure</h1>
      <p>
        A generated Mikata app starts as a small Vite project. Feature choices
        add focused files on top of that base instead of hiding the app behind
        a large framework directory.
      </p>

      <h2>Minimal app</h2>
      <p>
        The minimal scaffold contains the Vite shell, TypeScript config, the
        Mikata compiler plugin, and a single mounted component.
      </p>
      <CodeBlock html={baseTree} />
      <table>
        <thead>
          <tr>
            <th>File</th>
            <th>Purpose</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <code>vite.config.ts</code>
            </td>
            <td>Registers the Mikata JSX compiler.</td>
          </tr>
          <tr>
            <td>
              <code>tsconfig.json</code>
            </td>
            <td>Sets JSX types so TSX files understand Mikata elements.</td>
          </tr>
          <tr>
            <td>
              <code>src/main.tsx</code>
            </td>
            <td>Mounts the root component into the HTML entry.</td>
          </tr>
          <tr>
            <td>
              <code>src/App.tsx</code>
            </td>
            <td>Holds the starter UI and feature examples.</td>
          </tr>
        </tbody>
      </table>

      <h2>Client router app</h2>
      <p>
        Selecting <code>--router</code> keeps the app client-rendered and adds
        an explicit route table. <code>App.tsx</code> becomes the shell, while
        route components live in <code>src/pages</code>.
      </p>
      <CodeBlock html={routerTree} />

      <h2>Kit SSR app</h2>
      <p>
        Selecting <code>--kit</code> changes the shape of the project. Kit apps
        use file-based routes, a client entry for hydration, a server entry for
        rendering, and optional API route modules under <code>src/routes/api</code>.
      </p>
      <CodeBlock html={kitTree} />
      <table>
        <thead>
          <tr>
            <th>Path</th>
            <th>Role</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <code>src/routes/_layout.tsx</code>
            </td>
            <td>Wraps matched child routes and renders <code>routeOutlet()</code>.</td>
          </tr>
          <tr>
            <td>
              <code>src/routes/index.tsx</code>
            </td>
            <td>Defines the home page for <code>/</code>.</td>
          </tr>
          <tr>
            <td>
              <code>src/routes/[id].tsx</code>
            </td>
            <td>Creates a dynamic route segment when you add one.</td>
          </tr>
          <tr>
            <td>
              <code>src/routes/api/*.ts</code>
            </td>
            <td>Exports request handlers that run before page rendering.</td>
          </tr>
          <tr>
            <td>
              <code>src/entry-server.tsx</code>
            </td>
            <td>Calls <code>renderRoute</code> with the generated route manifest.</td>
          </tr>
          <tr>
            <td>
              <code>server.js</code>
            </td>
            <td>Serves the built client assets and dispatches SSR requests.</td>
          </tr>
        </tbody>
      </table>

      <h2>Feature files</h2>
      <p>
        Optional features add only the files they need. UI imports styles and
        wraps the app in <code>ThemeProvider</code>, form adds a{' '}
        <code>ContactForm</code>, i18n adds <code>src/i18n.ts</code>, testing
        adds <code>vitest.config.ts</code> and <code>src/App.test.tsx</code>,
        and Tailwind adds <code>src/index.css</code> plus PostCSS config.
      </p>

      <h2>Where next</h2>
      <ul>
        <li>
          <Link to="/start/first-app">Your first app</Link> explains the
          starter component model.
        </li>
        <li>
          <Link to="/app/file-routes">File routes</Link> covers Kit route
          discovery in depth.
        </li>
        <li>
          <Link to="/tooling/testing">Testing</Link> documents the generated
          Vitest setup.
        </li>
      </ul>
    </article>
  );
}
